"""Phoenix Company Platform V1.0 framework boundary."""

from phoenix_framework.company_platform.access import CompanyAccessService, CompanyCapabilityAccess
from phoenix_framework.company_platform.activity import CompanyActivityAdministrationService, CompanyActivityItem, CompanyActivityView
from phoenix_framework.company_platform.activity_audit_admin import CompanyActivityAuditAction, CompanyActivityAuditAdministrationExecutor, CompanyActivityAuditAdministrationRequest, CompanyActivityAuditAdministrationResult, CompanyActivityAuditAdministrationService
from phoenix_framework.company_platform.administration import CompanyAdministrationService, CompanyAdministrationView
from phoenix_framework.company_platform.audit import CompanyAuditItem, CompanyAuditService, CompanyAuditView
from phoenix_framework.company_platform.actions import CompanyAdministrationAction, CompanyAdministrationExecutor, CompanyAdministrationRequest, CompanyAdministrationResult, CompanyUserAction, CompanyUserAdministrationExecutor, CompanyUserAdministrationOperationService, CompanyUserAdministrationRequest
from phoenix_framework.company_platform.configuration_admin import CompanyConfigurationAction, CompanyConfigurationAdministrationExecutor, CompanyConfigurationAdministrationRequest, CompanyConfigurationAdministrationResult, CompanyConfigurationAdministrationService
from phoenix_framework.company_platform.contracts import COMPANY_PLATFORM_NAVIGATION, CompanyPlatformCapabilities, CompanyPlatformContract
from phoenix_framework.company_platform.context import CompanyPlatformContext
from phoenix_framework.company_platform.dashboard import CompanyDashboardService, CompanyDashboardSnapshot, CompanyDashboardView
from phoenix_framework.company_platform.document_admin import CompanyDocumentAction, CompanyDocumentAdministrationExecutor, CompanyDocumentAdministrationRequest, CompanyDocumentAdministrationResult, CompanyDocumentAdministrationService
from phoenix_framework.company_platform.integration_admin import CompanyIntegrationAction, CompanyIntegrationAdministrationExecutor, CompanyIntegrationAdministrationRequest, CompanyIntegrationAdministrationResult, CompanyIntegrationAdministrationService
from phoenix_framework.company_platform.module_experience_admin import CompanyModuleExperienceAction, CompanyModuleExperienceAdministrationExecutor, CompanyModuleExperienceAdministrationRequest, CompanyModuleExperienceAdministrationResult, CompanyModuleExperienceAdministrationService
from phoenix_framework.company_platform.navigation import CompanyNavigationService, CompanyNavigationView
from phoenix_framework.company_platform.notifications import CompanyNotificationItem, CompanyNotificationsService, CompanyNotificationsView
from phoenix_framework.company_platform.notifications_admin import CompanyNotificationAction, CompanyNotificationAdministrationExecutor, CompanyNotificationAdministrationRequest, CompanyNotificationAdministrationResult, CompanyNotificationAdministrationService
from phoenix_framework.company_platform.reporting import CompanyReportDefinitionView, CompanyReportResultView, CompanyReportingService, CompanyReportingView
from phoenix_framework.company_platform.reporting_admin import CompanyReportingAction, CompanyReportingAdministrationExecutor, CompanyReportingAdministrationRequest, CompanyReportingAdministrationResult, CompanyReportingAdministrationService
from phoenix_framework.company_platform.roles import CompanyPermissionView, CompanyRoleView, CompanyRolesPermissionsService, CompanyRolesPermissionsView
from phoenix_framework.company_platform.roles_admin import CompanyRoleAction, CompanyRoleAdministrationExecutor, CompanyRoleAdministrationRequest, CompanyRoleAdministrationService
from phoenix_framework.company_platform.users import CompanyUserAdministrationService, CompanyUserView, CompanyUsersView
from phoenix_framework.company_platform.user_visibility import CompanyUserVisibilityAction, CompanyUserVisibilityAdministrationExecutor, CompanyUserVisibilityAdministrationRequest, CompanyUserVisibilityAdministrationResult, CompanyUserVisibilityAdministrationService
from phoenix_framework.company_platform.visibility import DataVisibilityAdministrationService, DataVisibilityRuleView, DataVisibilityView
from phoenix_framework.company_platform.visibility_admin import CompanyVisibilityAction, CompanyVisibilityAdministrationExecutor, CompanyVisibilityAdministrationRequest, CompanyVisibilityAdministrationResult, CompanyVisibilityAdministrationService
from phoenix_framework.company_platform.workspaces import CompanyWorkspaceAdministrationService, CompanyWorkspacesView, WorkspaceView
from phoenix_framework.company_platform.workspaces_admin import CompanyWorkspaceAction, CompanyWorkspaceAdministrationExecutor, CompanyWorkspaceAdministrationOperationService, CompanyWorkspaceAdministrationRequest, CompanyWorkspaceAdministrationResult
from phoenix_framework.company_platform.workspace_assignments import CompanyWorkspaceAssignmentAction, CompanyWorkspaceAssignmentExecutor, CompanyWorkspaceAssignmentRequest, CompanyWorkspaceAssignmentResult, CompanyWorkspaceAssignmentService
from phoenix_framework.company_platform.workflow_admin import CompanyWorkflowAction, CompanyWorkflowAdministrationExecutor, CompanyWorkflowAdministrationRequest, CompanyWorkflowAdministrationResult, CompanyWorkflowAdministrationService

__all__ = [
    "COMPANY_PLATFORM_NAVIGATION", "CompanyAccessService", "CompanyActivityAdministrationService", "CompanyActivityAuditAction", "CompanyActivityAuditAdministrationExecutor", "CompanyActivityAuditAdministrationRequest", "CompanyActivityAuditAdministrationResult", "CompanyActivityAuditAdministrationService", "CompanyActivityItem", "CompanyActivityView",
    "CompanyAdministrationAction", "CompanyAdministrationExecutor", "CompanyAdministrationRequest", "CompanyAdministrationResult", "CompanyAdministrationService", "CompanyAdministrationView",
    "CompanyAuditItem", "CompanyAuditService", "CompanyAuditView", "CompanyCapabilityAccess", "CompanyConfigurationAction", "CompanyConfigurationAdministrationExecutor", "CompanyConfigurationAdministrationRequest", "CompanyConfigurationAdministrationResult", "CompanyConfigurationAdministrationService", "CompanyDashboardService", "CompanyDashboardSnapshot", "CompanyDashboardView",
    "CompanyDocumentAction", "CompanyDocumentAdministrationExecutor", "CompanyDocumentAdministrationRequest", "CompanyDocumentAdministrationResult", "CompanyDocumentAdministrationService",
    "CompanyIntegrationAction", "CompanyIntegrationAdministrationExecutor", "CompanyIntegrationAdministrationRequest", "CompanyIntegrationAdministrationResult", "CompanyIntegrationAdministrationService",
    "CompanyModuleExperienceAction", "CompanyModuleExperienceAdministrationExecutor", "CompanyModuleExperienceAdministrationRequest", "CompanyModuleExperienceAdministrationResult", "CompanyModuleExperienceAdministrationService",
    "CompanyNavigationService", "CompanyNavigationView", "CompanyNotificationAction", "CompanyNotificationAdministrationExecutor", "CompanyNotificationAdministrationRequest", "CompanyNotificationAdministrationResult", "CompanyNotificationAdministrationService", "CompanyNotificationItem", "CompanyNotificationsService", "CompanyNotificationsView", "CompanyPermissionView",
    "CompanyPlatformCapabilities", "CompanyPlatformContract", "CompanyPlatformContext", "CompanyReportDefinitionView", "CompanyReportResultView", "CompanyReportingService", "CompanyReportingView",
    "CompanyReportingAction", "CompanyReportingAdministrationExecutor", "CompanyReportingAdministrationRequest", "CompanyReportingAdministrationResult", "CompanyReportingAdministrationService",
    "CompanyRoleAction", "CompanyRoleAdministrationExecutor", "CompanyRoleAdministrationRequest", "CompanyRoleAdministrationService", "CompanyRoleView", "CompanyRolesPermissionsService", "CompanyRolesPermissionsView",
    "CompanyUserAction", "CompanyUserAdministrationExecutor", "CompanyUserAdministrationOperationService", "CompanyUserAdministrationRequest", "CompanyUserAdministrationService", "CompanyUserView", "CompanyUsersView",
    "CompanyUserVisibilityAction", "CompanyUserVisibilityAdministrationExecutor", "CompanyUserVisibilityAdministrationRequest", "CompanyUserVisibilityAdministrationResult", "CompanyUserVisibilityAdministrationService",
    "CompanyVisibilityAction", "CompanyVisibilityAdministrationExecutor", "CompanyVisibilityAdministrationRequest", "CompanyVisibilityAdministrationResult", "CompanyVisibilityAdministrationService", "DataVisibilityAdministrationService", "DataVisibilityRuleView", "DataVisibilityView",
    "CompanyWorkspaceAction", "CompanyWorkspaceAdministrationExecutor", "CompanyWorkspaceAdministrationOperationService", "CompanyWorkspaceAdministrationRequest", "CompanyWorkspaceAdministrationResult", "CompanyWorkspaceAdministrationService", "CompanyWorkspacesView",
    "CompanyWorkspaceAssignmentAction", "CompanyWorkspaceAssignmentExecutor", "CompanyWorkspaceAssignmentRequest", "CompanyWorkspaceAssignmentResult", "CompanyWorkspaceAssignmentService", "WorkspaceView",
    "CompanyWorkflowAction", "CompanyWorkflowAdministrationExecutor", "CompanyWorkflowAdministrationRequest", "CompanyWorkflowAdministrationResult", "CompanyWorkflowAdministrationService",
]
