import { useEffect, useState } from 'react'

type Channel = { id: string; channel_type: string; name: string; visibility: string; created_at: string }
type Message = { id: string; sender_identity_id: string; content: string; created_at: string }
type ApiResponse<T> = { data?: T; request_id?: string }

async function api<T>(url: string, init?: RequestInit): Promise<T> {
  const response = await fetch(url, { credentials: 'include', ...init, headers: { 'Content-Type': 'application/json', ...(init?.headers ?? {}) } })
  const body = await response.json().catch(() => ({})) as ApiResponse<T> & { message?: string }
  if (!response.ok) throw new Error(body.message || 'Phoenix Core request failed.')
  return body.data as T
}

export function Connect() {
  const [channels, setChannels] = useState<Channel[]>([]); const [activeId, setActiveId] = useState(''); const [messages, setMessages] = useState<Message[]>([])
  const [draft, setDraft] = useState(''); const [loading, setLoading] = useState(true); const [sending, setSending] = useState(false); const [notice, setNotice] = useState('')
  const [newOpen, setNewOpen] = useState(false); const [newType, setNewType] = useState<'DIRECT' | 'GROUP'>('GROUP'); const [newName, setNewName] = useState(''); const [targetId, setTargetId] = useState(''); const [members, setMembers] = useState('')
  const [presence, setPresence] = useState('ONLINE'); const [memberOpen, setMemberOpen] = useState(false); const [memberId, setMemberId] = useState(''); const [memberSaving, setMemberSaving] = useState(false)

  const loadChannels = async () => { setLoading(true); setNotice(''); try { const result = await api<{ items: Channel[] }>('/api/v1/connect/channels'); const items = result?.items ?? []; setChannels(items); if (!activeId && items[0]) setActiveId(items[0].id); if (activeId && !items.some(c => c.id === activeId)) setActiveId(items[0]?.id ?? '') } catch (error) { setNotice(error instanceof Error ? error.message : 'Unable to load Connect.') } finally { setLoading(false) } }
  const loadMessages = async (channelId: string) => { if (!channelId) return; try { const result = await api<{ items: Message[] }>(`/api/v1/connect/channels/${channelId}/messages?limit=100`); setMessages([...(result?.items ?? [])].reverse()); await api(`/api/v1/connect/channels/${channelId}/read`, { method: 'POST', body: JSON.stringify({}) }) } catch (error) { setNotice(error instanceof Error ? error.message : 'Unable to load messages.') } }
  useEffect(() => { void loadChannels() }, [])
  useEffect(() => { if (activeId) void loadMessages(activeId) }, [activeId])
  useEffect(() => { void updatePresence('ONLINE') }, [])

  const updatePresence = async (status: string) => { try { await api('/api/v1/connect/presence', { method: 'POST', body: JSON.stringify({ status }) }); setPresence(status) } catch (error) { setNotice(error instanceof Error ? error.message : 'Unable to update presence.') } }
  const addMember = async () => { if (!activeId || !memberId.trim() || memberSaving) return; setMemberSaving(true); setNotice(''); try { await api(`/api/v1/connect/channels/${activeId}/members`, { method: 'POST', body: JSON.stringify({ identity_id: memberId.trim() }) }); setMemberId(''); setMemberOpen(false); setNotice('Member added.') } catch (error) { setNotice(error instanceof Error ? error.message : 'Unable to add member.') } finally { setMemberSaving(false) } }
  const send = async () => { if (!activeId || !draft.trim() || sending) return; setSending(true); setNotice(''); try { await api(`/api/v1/connect/channels/${activeId}/messages`, { method: 'POST', body: JSON.stringify({ content: draft.trim() }) }); setDraft(''); await loadMessages(activeId) } catch (error) { setNotice(error instanceof Error ? error.message : 'Unable to send message.') } finally { setSending(false) } }
  const react = async (messageId: string, reaction: string) => { try { await api(`/api/v1/connect/messages/${messageId}/reactions`, { method: 'POST', body: JSON.stringify({ reaction }) }); setNotice('Reaction added.') } catch (error) { setNotice(error instanceof Error ? error.message : 'Unable to add reaction.') } }
  const createConversation = async () => { setNotice(''); try { let channel: Channel; if (newType === 'DIRECT') { if (!targetId.trim()) throw new Error('Target identity ID is required.'); channel = await api<Channel>('/api/v1/connect/channels/direct', { method: 'POST', body: JSON.stringify({ target_identity_id: targetId.trim() }) }) } else { if (!newName.trim()) throw new Error('Group name is required.'); const member_identity_ids = members.split(',').map(value => value.trim()).filter(Boolean); channel = await api<Channel>('/api/v1/connect/channels/group', { method: 'POST', body: JSON.stringify({ name: newName.trim(), member_identity_ids, visibility: 'PRIVATE' }) }) } setNewOpen(false); setNewName(''); setTargetId(''); setMembers(''); await loadChannels(); setActiveId(channel.id) } catch (error) { setNotice(error instanceof Error ? error.message : 'Unable to create conversation.') } }

  const active = channels.find(channel => channel.id === activeId)
  return <div className="connect-page">
    <div className="connect-toolbar"><div><span className="section-label">PHOENIX CONNECT</span><h3>Company communication</h3></div><div className="connect-actions"><select className="refresh-button" value={presence} onChange={event => void updatePresence(event.target.value)} aria-label="Presence status"><option value="ONLINE">Online</option><option value="AWAY">Away</option><option value="OFFLINE">Offline</option></select><button className="primary-action" onClick={() => setNewOpen(true)}>New conversation</button><button className="refresh-button" onClick={() => void loadChannels()}>Refresh</button></div></div>
    {newOpen && <div className="connect-new-panel"><div className="connect-new-head"><strong>New conversation</strong><button className="row-action" onClick={() => setNewOpen(false)}>Close</button></div><div className="connect-new-fields"><select value={newType} onChange={event => setNewType(event.target.value as 'DIRECT' | 'GROUP')}><option value="GROUP">Group</option><option value="DIRECT">Direct</option></select>{newType === 'GROUP' ? <><input value={newName} onChange={event => setNewName(event.target.value)} placeholder="Group name" /><input value={members} onChange={event => setMembers(event.target.value)} placeholder="Member identity IDs, comma separated" /></> : <input value={targetId} onChange={event => setTargetId(event.target.value)} placeholder="Target identity ID" />}<button className="primary-action" onClick={() => void createConversation()}>Create</button></div></div>}
    <div className="connect-shell"><aside className="connect-channels"><div className="connect-heading">CONVERSATIONS</div>{loading ? <div className="connect-empty">Loading…</div> : channels.length === 0 ? <div className="connect-empty">No conversations yet.</div> : channels.map(channel => <button key={channel.id} className={`connect-channel ${activeId === channel.id ? 'active' : ''}`} onClick={() => setActiveId(channel.id)}><span className="connect-channel-dot" /><span><strong>{channel.name}</strong><small>{channel.channel_type}</small></span></button>)}</aside><section className="connect-conversation">{active ? <><header className="connect-conversation-header"><div><strong>{active.name}</strong><span>{active.channel_type} · {active.visibility}</span></div><button className="row-action" onClick={() => setMemberOpen(value => !value)}>Add member</button></header>{memberOpen && <div className="connect-member-panel"><input value={memberId} onChange={event => setMemberId(event.target.value)} placeholder="Member identity ID" /><button className="primary-action" onClick={() => void addMember()} disabled={memberSaving || !memberId.trim()}>{memberSaving ? 'Adding…' : 'Add'}</button></div>}<div className="connect-messages">{messages.length === 0 ? <div className="connect-empty">No messages in this conversation.</div> : messages.map(message => <article className="connect-message" key={message.id}><div className="connect-message-avatar">{message.sender_identity_id.slice(0, 2).toUpperCase()}</div><div><div className="connect-message-meta"><strong>{message.sender_identity_id.slice(0, 8)}</strong><time>{new Date(message.created_at).toLocaleString()}</time></div><p>{message.content}</p><button className="message-reaction" onClick={() => void react(message.id, '👍')}>👍</button></div></article>)}</div><div className="connect-composer"><input value={draft} onChange={event => setDraft(event.target.value)} onKeyDown={event => { if (event.key === 'Enter' && !event.shiftKey) { event.preventDefault(); void send() } }} placeholder="Write a message…" disabled={sending} /><button className="primary-action" onClick={() => void send()} disabled={sending || !draft.trim()}>{sending ? 'Sending…' : 'Send'}</button></div></> : <div className="connect-empty">Select a conversation to begin.</div>}</section></div>{notice && <div className="inline-notice">{notice}</div>}</div>
}
